apiVersion: v1
kind: Service
metadata:
  name: backend-feed
spec:
  type: ClusterIP  # Change to LoadBalancer if you want external access
  ports:
  - port: 8080  # The port that the service will expose
    targetPort: 8080  # The port on the container
  selector:
    app: backend-feed
