apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  type: LoadBalancer  # Change to ClusterIP if you want internal access only
  ports:
  - port: 8080  # The port that the service will expose
    targetPort: 8080  # The port on the container
  selector:
    app: reverseproxy
