apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <your_dockerhub_username>/udagram-frontend:<tag>  # Replace with your Docker image
        ports:
        - containerPort: 8080  # Adjust the port if necessary
        env:
        - name: API_HOST
          value: "http://reverseproxy:8080/api/v0"  # Adjust the API endpoint as needed
